### PR TITLE
Allow any class names to be exported

### PR DESCRIPTION
**Pull request by bushee**
This change allows any possible class name to be exported - even those whose names don't comply with typescript variable name constraints.

Addresses problem from issue #6.

### CODE REVIEW

**Comment by silbinarywolf** [comment]
Maybe add a test that uses a hyphen for a class name? ie. 'Class--Name'
Just so it's less likely to be broken in the future / accidentally regressed :)

**Comment by bushee** [comment]
@silbinarywolf good point, idk why I haven't thought of it myself :(

**Comment by stephankaag** [comment]
This stylesheet still gives problems:

```:host {
background: 'blue';
}
```

->

```// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  ')(false);
// Module
exports.push([module.id, ': string;
}
declare var cssExports: CssExports;
export = cssExports;
```

**Comment by mattsjones** [comment]
Hey Bud, This is a nice solution to the problem, thanks for working this out. 

Can you just remove the "`Doesn't silently ignore invalid TypeScript identifiers. If a class name is not valid TypeScript (e.g. .foo-bar, instead of .fooBar), tsc should report an error.`" line from the README as it's no longer valid.

**Comment by mattsjones** [comment]
@stephankaag Your issue is unrelated to this one as it's broken with both approaches. Feel free to submit a separate PR to resolve it.

**Comment by bushee** [comment]
@mattsjones I'm on it :)

**Pull request merged**
